baseURL = "http://example.org/"
languageCode = "en-us"
title = "The red thread"
theme = "book"

##[menu]
##[[menu.before]]
##[[menu.after]]
##  name = "Github"
##  url = "https://github.com/alex-shpak/hugo-book"
##  weight = 10

##[[menu.after]]
##  name = "Hugo Themes"
##  url = "https://themes.gohugo.io/hugo-book/"
##  weight = 20

[params]
    BookToC = false
    BookSearch = false
    BookComments = false


  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = '*'
